window.vocabularyData = [
  {
    german: "das Haus",
    plural: "die Häuser",
    pronunciationEn: "dahs hows",
    pronunciationBn: "দাস হাউস",
    meaningEn: "house",
    meaningBn: "বাড়ি",
    exampleDe: "Das Haus ist sehr alt.",
    exampleEn: "The house is very old.",
    level: "A2",
    category: "Home"
  },
  {
    german: "das Zimmer",
    plural: "die Zimmer",
    pronunciationEn: "dahs TSIM-er",
    pronunciationBn: "দাস ৎসিমার",
    meaningEn: "room",
    meaningBn: "ঘর",
    exampleDe: "Mein Zimmer ist klein, aber hell.",
    exampleEn: "My room is small, but bright.",
    level: "A2",
    category: "Home"
  },
  {
    german: "der Tisch",
    plural: "die Tische",
    pronunciationEn: "dair tish",
    pronunciationBn: "ডেয়ার টিশ",
    meaningEn: "table",
    meaningBn: "টেবিল",
    exampleDe: "Das Buch liegt auf dem Tisch.",
    exampleEn: "The book is on the table.",
    level: "A2",
    category: "Home"
  },
  {
    german: "die Küche",
    plural: "die Küchen",
    pronunciationEn: "dee KUE-khe",
    pronunciationBn: "দি কুখে",
    meaningEn: "kitchen",
    meaningBn: "রান্নাঘর",
    exampleDe: "In der Küche kocht meine Mutter.",
    exampleEn: "My mother is cooking in the kitchen.",
    level: "A2",
    category: "Home"
  },
  {
    german: "wohnen",
    pronunciationEn: "VOH-nen",
    pronunciationBn: "ভোনেন",
    meaningEn: "to live, reside",
    meaningBn: "বাস করা",
    exampleDe: "Wir wohnen in einer kleinen Stadt.",
    exampleEn: "We live in a small city.",
    level: "A2",
    category: "Home"
  },
  {
    german: "schlafen",
    pronunciationEn: "SHLAH-fen",
    pronunciationBn: "শ্লাফেন",
    meaningEn: "to sleep",
    meaningBn: "ঘুমানো",
    exampleDe: "Das Kind schläft schon.",
    exampleEn: "The child is already sleeping.",
    level: "A2",
    category: "Home"
  },
  {
    german: "sauber",
    pronunciationEn: "ZOW-ber",
    pronunciationBn: "জাউবার",
    meaningEn: "clean",
    meaningBn: "পরিষ্কার",
    exampleDe: "Das Bad ist heute sauber.",
    exampleEn: "The bathroom is clean today.",
    level: "A2",
    category: "Home"
  },
  {
    german: "bequem",
    pronunciationEn: "beh-KVAYM",
    pronunciationBn: "বেকভেম",
    meaningEn: "comfortable",
    meaningBn: "আরামদায়ক",
    exampleDe: "Der Stuhl ist sehr bequem.",
    exampleEn: "The chair is very comfortable.",
    level: "B1",
    category: "Home"
  },
  {
    german: "die Familie",
    plural: "die Familien",
    pronunciationEn: "dee fah-MEE-lee-uh",
    pronunciationBn: "দি ফামিলিয়ে",
    meaningEn: "family",
    meaningBn: "পরিবার",
    exampleDe: "Meine Familie lebt in Dhaka.",
    exampleEn: "My family lives in Dhaka.",
    level: "A2",
    category: "People"
  },
  {
    german: "der Freund",
    plural: "die Freunde",
    pronunciationEn: "dair froynt",
    pronunciationBn: "ডেয়ার ফ্রয়ন্ট",
    meaningEn: "friend",
    meaningBn: "বন্ধু",
    exampleDe: "Mein Freund kommt morgen zu Besuch.",
    exampleEn: "My friend is coming to visit tomorrow.",
    level: "A2",
    category: "People"
  },
  {
    german: "die Nachbarin",
    plural: "die Nachbarinnen",
    pronunciationEn: "dee NAKH-ba-rin",
    pronunciationBn: "দি নাখবারিন",
    meaningEn: "female neighbor",
    meaningBn: "প্রতিবেশিনী",
    exampleDe: "Meine Nachbarin ist sehr nett.",
    exampleEn: "My neighbor is very kind.",
    level: "B1",
    category: "People"
  },
  {
    german: "das Kind",
    plural: "die Kinder",
    pronunciationEn: "dahs kint",
    pronunciationBn: "দাস কিন্ট",
    meaningEn: "child",
    meaningBn: "শিশু",
    exampleDe: "Das Kind malt ein Bild.",
    exampleEn: "The child is drawing a picture.",
    level: "A2",
    category: "People"
  },
  {
    german: "helfen",
    pronunciationEn: "HEL-fen",
    pronunciationBn: "হেলফেন",
    meaningEn: "to help",
    meaningBn: "সাহায্য করা",
    exampleDe: "Kannst du mir bitte helfen?",
    exampleEn: "Can you please help me?",
    level: "A2",
    category: "People"
  },
  {
    german: "lachen",
    pronunciationEn: "LAKH-en",
    pronunciationBn: "লাখেন",
    meaningEn: "to laugh",
    meaningBn: "হাসা",
    exampleDe: "Wir lachen über den Witz.",
    exampleEn: "We laugh about the joke.",
    level: "A2",
    category: "People"
  },
  {
    german: "freundlich",
    pronunciationEn: "FROYND-likh",
    pronunciationBn: "ফ্রয়ন্ডলিশ",
    meaningEn: "friendly",
    meaningBn: "বন্ধুসুলভ",
    exampleDe: "Die Lehrerin ist freundlich und ruhig.",
    exampleEn: "The teacher is friendly and calm.",
    level: "A2",
    category: "People"
  },
  {
    german: "geduldig",
    pronunciationEn: "geh-DOOL-dikh",
    pronunciationBn: "গেদুলডিশ",
    meaningEn: "patient",
    meaningBn: "ধৈর্যশীল",
    exampleDe: "Mein Vater ist sehr geduldig.",
    exampleEn: "My father is very patient.",
    level: "B1",
    category: "People"
  },
  {
    german: "das Brot",
    plural: "die Brote",
    pronunciationEn: "dahs broht",
    pronunciationBn: "দাস ব্রোট",
    meaningEn: "bread",
    meaningBn: "রুটি",
    exampleDe: "Ich kaufe frisches Brot.",
    exampleEn: "I buy fresh bread.",
    level: "A2",
    category: "Food"
  },
  {
    german: "die Milch",
    plural: "kein Plural",
    pronunciationEn: "dee milkh",
    pronunciationBn: "দি মিলখ",
    meaningEn: "milk",
    meaningBn: "দুধ",
    exampleDe: "Im Kaffee ist keine Milch.",
    exampleEn: "There is no milk in the coffee.",
    level: "A2",
    category: "Food"
  },
  {
    german: "das Wasser",
    plural: "kein Plural",
    pronunciationEn: "dahs VAH-ser",
    pronunciationBn: "দাস ভাসার",
    meaningEn: "water",
    meaningBn: "পানি",
    exampleDe: "Bitte trink mehr Wasser.",
    exampleEn: "Please drink more water.",
    level: "A2",
    category: "Food"
  },
  {
    german: "der Apfel",
    plural: "die Äpfel",
    pronunciationEn: "dair AP-fel",
    pronunciationBn: "ডেয়ার আপফেল",
    meaningEn: "apple",
    meaningBn: "আপেল",
    exampleDe: "Der Apfel schmeckt sehr gut.",
    exampleEn: "The apple tastes very good.",
    level: "A2",
    category: "Food"
  },
  {
    german: "kaufen",
    pronunciationEn: "KOW-fen",
    pronunciationBn: "কাউফেন",
    meaningEn: "to buy",
    meaningBn: "কেনা",
    exampleDe: "Wir kaufen Obst auf dem Markt.",
    exampleEn: "We buy fruit at the market.",
    level: "A2",
    category: "Food"
  },
  {
    german: "kochen",
    pronunciationEn: "KHO-khen",
    pronunciationBn: "কোখেন",
    meaningEn: "to cook",
    meaningBn: "রান্না করা",
    exampleDe: "Ich koche heute Reis und Gemüse.",
    exampleEn: "I am cooking rice and vegetables today.",
    level: "A2",
    category: "Food"
  },
  {
    german: "frisch",
    pronunciationEn: "frish",
    pronunciationBn: "ফ্রিশ",
    meaningEn: "fresh",
    meaningBn: "তাজা",
    exampleDe: "Das Brot ist noch frisch.",
    exampleEn: "The bread is still fresh.",
    level: "A2",
    category: "Food"
  },
  {
    german: "günstig",
    pronunciationEn: "GUENS-tikh",
    pronunciationBn: "গ্যুনস্টিশ",
    meaningEn: "inexpensive, affordable",
    meaningBn: "সাশ্রয়ী",
    exampleDe: "Dieses Café ist ziemlich günstig.",
    exampleEn: "This cafe is quite affordable.",
    level: "B1",
    category: "Food"
  },
  {
    german: "der Bahnhof",
    plural: "die Bahnhöfe",
    pronunciationEn: "dair BAHN-hohf",
    pronunciationBn: "ডেয়ার বানহফ",
    meaningEn: "train station",
    meaningBn: "রেলস্টেশন",
    exampleDe: "Der Bahnhof ist nicht weit von hier.",
    exampleEn: "The train station is not far from here.",
    level: "A2",
    category: "Travel"
  },
  {
    german: "die Straße",
    plural: "die Straßen",
    pronunciationEn: "dee SHTRAH-se",
    pronunciationBn: "দি শ্ট্রাসে",
    meaningEn: "street",
    meaningBn: "রাস্তা",
    exampleDe: "Die Straße ist heute sehr ruhig.",
    exampleEn: "The street is very quiet today.",
    level: "A2",
    category: "Travel"
  },
  {
    german: "die Stadt",
    plural: "die Städte",
    pronunciationEn: "dee shtaht",
    pronunciationBn: "দি শ্টাট",
    meaningEn: "city",
    meaningBn: "শহর",
    exampleDe: "Berlin ist eine große Stadt.",
    exampleEn: "Berlin is a big city.",
    level: "A2",
    category: "Travel"
  },
  {
    german: "das Ticket",
    plural: "die Tickets",
    pronunciationEn: "dahs TIK-et",
    pronunciationBn: "দাস টিকেট",
    meaningEn: "ticket",
    meaningBn: "টিকিট",
    exampleDe: "Ich habe mein Ticket schon gekauft.",
    exampleEn: "I have already bought my ticket.",
    level: "A2",
    category: "Travel"
  },
  {
    german: "fahren",
    pronunciationEn: "FAH-ren",
    pronunciationBn: "ফারেন",
    meaningEn: "to travel, drive, go by vehicle",
    meaningBn: "যানবাহনে যাওয়া",
    exampleDe: "Wir fahren morgen nach Hamburg.",
    exampleEn: "We are traveling to Hamburg tomorrow.",
    level: "A2",
    category: "Travel"
  },
  {
    german: "ankommen",
    pronunciationEn: "AHN-kom-men",
    pronunciationBn: "আনকোমেন",
    meaningEn: "to arrive",
    meaningBn: "পৌঁছানো",
    exampleDe: "Der Zug kommt um acht Uhr an.",
    exampleEn: "The train arrives at eight o'clock.",
    level: "B1",
    category: "Travel"
  },
  {
    german: "links",
    pronunciationEn: "links",
    pronunciationBn: "লিংকস",
    meaningEn: "left",
    meaningBn: "বাম দিকে",
    exampleDe: "Die Apotheke ist links.",
    exampleEn: "The pharmacy is on the left.",
    level: "A2",
    category: "Travel"
  },
  {
    german: "nah",
    pronunciationEn: "nah",
    pronunciationBn: "না",
    meaningEn: "near",
    meaningBn: "কাছে",
    exampleDe: "Die Schule ist ganz nah.",
    exampleEn: "The school is very near.",
    level: "A2",
    category: "Travel"
  },
  {
    german: "der Morgen",
    plural: "die Morgen",
    pronunciationEn: "dair MOR-gen",
    pronunciationBn: "ডেয়ার মরগেন",
    meaningEn: "morning",
    meaningBn: "সকাল",
    exampleDe: "Am Morgen trinke ich Tee.",
    exampleEn: "In the morning I drink tea.",
    level: "A2",
    category: "Time"
  },
  {
    german: "der Abend",
    plural: "die Abende",
    pronunciationEn: "dair AH-bent",
    pronunciationBn: "ডেয়ার আবেন্ট",
    meaningEn: "evening",
    meaningBn: "সন্ধ্যা",
    exampleDe: "Am Abend lese ich ein Buch.",
    exampleEn: "In the evening I read a book.",
    level: "A2",
    category: "Time"
  },
  {
    german: "die Woche",
    plural: "die Wochen",
    pronunciationEn: "dee VO-khe",
    pronunciationBn: "দি ভোখে",
    meaningEn: "week",
    meaningBn: "সপ্তাহ",
    exampleDe: "Diese Woche ist sehr stressig.",
    exampleEn: "This week is very stressful.",
    level: "A2",
    category: "Time"
  },
  {
    german: "das Wochenende",
    plural: "die Wochenenden",
    pronunciationEn: "dahs VOKH-en-en-de",
    pronunciationBn: "দাস ভোখেনএন্ডে",
    meaningEn: "weekend",
    meaningBn: "সপ্তাহান্ত",
    exampleDe: "Am Wochenende besuchen wir Freunde.",
    exampleEn: "We visit friends on the weekend.",
    level: "A2",
    category: "Time"
  },
  {
    german: "beginnen",
    pronunciationEn: "beh-GIN-nen",
    pronunciationBn: "বেগিন্নেন",
    meaningEn: "to begin",
    meaningBn: "শুরু করা",
    exampleDe: "Der Kurs beginnt um neun Uhr.",
    exampleEn: "The course begins at nine o'clock.",
    level: "A2",
    category: "Time"
  },
  {
    german: "dauern",
    pronunciationEn: "DOW-ern",
    pronunciationBn: "ডাউয়ার্ন",
    meaningEn: "to last, take time",
    meaningBn: "স্থায়ী হওয়া",
    exampleDe: "Der Film dauert zwei Stunden.",
    exampleEn: "The film lasts two hours.",
    level: "B1",
    category: "Time"
  },
  {
    german: "früh",
    pronunciationEn: "froo",
    pronunciationBn: "ফ্রু",
    meaningEn: "early",
    meaningBn: "ভোরে, আগে",
    exampleDe: "Ich stehe morgen früh auf.",
    exampleEn: "I get up early tomorrow.",
    level: "A2",
    category: "Time"
  },
  {
    german: "spät",
    pronunciationEn: "shpayt",
    pronunciationBn: "শ্পেট",
    meaningEn: "late",
    meaningBn: "দেরি",
    exampleDe: "Heute komme ich spät nach Hause.",
    exampleEn: "Today I come home late.",
    level: "A2",
    category: "Time"
  },
  {
    german: "die Schule",
    plural: "die Schulen",
    pronunciationEn: "dee SHOO-le",
    pronunciationBn: "দি শুলে",
    meaningEn: "school",
    meaningBn: "স্কুল",
    exampleDe: "Die Schule beginnt um acht Uhr.",
    exampleEn: "School starts at eight o'clock.",
    level: "A2",
    category: "Study"
  },
  {
    german: "der Lehrer",
    plural: "die Lehrer",
    pronunciationEn: "dair LAY-rer",
    pronunciationBn: "ডেয়ার লেরার",
    meaningEn: "teacher",
    meaningBn: "শিক্ষক",
    exampleDe: "Der Lehrer erklärt die Aufgabe.",
    exampleEn: "The teacher explains the exercise.",
    level: "A2",
    category: "Study"
  },
  {
    german: "die Aufgabe",
    plural: "die Aufgaben",
    pronunciationEn: "dee OWF-gah-buh",
    pronunciationBn: "দি আউফগাবে",
    meaningEn: "task, exercise",
    meaningBn: "কাজ, অনুশীলনী",
    exampleDe: "Die Aufgabe ist nicht leicht.",
    exampleEn: "The exercise is not easy.",
    level: "A2",
    category: "Study"
  },
  {
    german: "der Beruf",
    plural: "die Berufe",
    pronunciationEn: "dair beh-ROOF",
    pronunciationBn: "ডেয়ার বেরুফ",
    meaningEn: "profession, job",
    meaningBn: "পেশা",
    exampleDe: "Welcher Beruf interessiert dich?",
    exampleEn: "Which profession interests you?",
    level: "B1",
    category: "Study"
  },
  {
    german: "lernen",
    pronunciationEn: "LERN-en",
    pronunciationBn: "লার্নেন",
    meaningEn: "to learn, study",
    meaningBn: "শেখা, পড়া",
    exampleDe: "Ich lerne jeden Tag Deutsch.",
    exampleEn: "I study German every day.",
    level: "A2",
    category: "Study"
  },
  {
    german: "erklären",
    pronunciationEn: "air-KLEH-ren",
    pronunciationBn: "এরক্লেরেন",
    meaningEn: "to explain",
    meaningBn: "ব্যাখ্যা করা",
    exampleDe: "Kannst du das bitte erklären?",
    exampleEn: "Can you please explain that?",
    level: "B1",
    category: "Study"
  },
  {
    german: "schwierig",
    pronunciationEn: "SHVEE-rikh",
    pronunciationBn: "শ্ভীরিশ",
    meaningEn: "difficult",
    meaningBn: "কঠিন",
    exampleDe: "Diese Grammatik ist schwierig.",
    exampleEn: "This grammar is difficult.",
    level: "A2",
    category: "Study"
  },
  {
    german: "erfolgreich",
    pronunciationEn: "air-FOLG-rikeh",
    pronunciationBn: "এরফলগ্রাইখ",
    meaningEn: "successful",
    meaningBn: "সফল",
    exampleDe: "Sie ist eine erfolgreiche Studentin.",
    exampleEn: "She is a successful student.",
    level: "B1",
    category: "Study"
  },
  {
    german: "die Frage",
    plural: "die Fragen",
    pronunciationEn: "dee FRAH-guh",
    pronunciationBn: "দি ফ্রাগে",
    meaningEn: "question",
    meaningBn: "প্রশ্ন",
    exampleDe: "Ich habe eine wichtige Frage.",
    exampleEn: "I have an important question.",
    level: "A2",
    category: "Communication"
  },
  {
    german: "die Antwort",
    plural: "die Antworten",
    pronunciationEn: "dee ANT-vort",
    pronunciationBn: "দি আন্টভর্ট",
    meaningEn: "answer",
    meaningBn: "উত্তর",
    exampleDe: "Seine Antwort war sehr klar.",
    exampleEn: "His answer was very clear.",
    level: "A2",
    category: "Communication"
  },
  {
    german: "das Problem",
    plural: "die Probleme",
    pronunciationEn: "dahs proh-BLAYM",
    pronunciationBn: "দাস প্রোব্লেম",
    meaningEn: "problem",
    meaningBn: "সমস্যা",
    exampleDe: "Wir lösen das Problem zusammen.",
    exampleEn: "We solve the problem together.",
    level: "A2",
    category: "Communication"
  },
  {
    german: "die Idee",
    plural: "die Ideen",
    pronunciationEn: "dee ee-DAY",
    pronunciationBn: "দি ইদে",
    meaningEn: "idea",
    meaningBn: "ধারণা",
    exampleDe: "Das ist eine gute Idee.",
    exampleEn: "That is a good idea.",
    level: "A2",
    category: "Communication"
  },
  {
    german: "fragen",
    pronunciationEn: "FRAH-gen",
    pronunciationBn: "ফ্রাগেন",
    meaningEn: "to ask",
    meaningBn: "জিজ্ঞেস করা",
    exampleDe: "Ich frage den Lehrer nach dem Wort.",
    exampleEn: "I ask the teacher about the word.",
    level: "A2",
    category: "Communication"
  },
  {
    german: "antworten",
    pronunciationEn: "ANT-vor-ten",
    pronunciationBn: "আন্টভর্টেন",
    meaningEn: "to answer",
    meaningBn: "উত্তর দেওয়া",
    exampleDe: "Bitte antworte kurz auf die E-Mail.",
    exampleEn: "Please answer the email briefly.",
    level: "A2",
    category: "Communication"
  },
  {
    german: "klar",
    pronunciationEn: "klahr",
    pronunciationBn: "ক্লার",
    meaningEn: "clear",
    meaningBn: "স্পষ্ট",
    exampleDe: "Die Erklärung ist jetzt klar.",
    exampleEn: "The explanation is clear now.",
    level: "A2",
    category: "Communication"
  },
  {
    german: "möglich",
    pronunciationEn: "MUH-glikh",
    pronunciationBn: "ম্যোগলিশ",
    meaningEn: "possible",
    meaningBn: "সম্ভব",
    exampleDe: "Ist ein Treffen morgen möglich?",
    exampleEn: "Is a meeting possible tomorrow?",
    level: "B1",
    category: "Communication"
  }
];
